[tool.ruff]
target-version = "py312"
line-length = 88
# Включите правила, которые вы хотите применить
extend-ignore = ["E501"]  # Игнорировать ошибки длины строки (если необходимо)

# Для автоматического исправления
fix = true
