name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.5'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip freeze > requirements.txt
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pip install fastapi[all]
        pytest api/tests 
