name: Python package

on: 
  push:
    branches:
      - feature/api

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
       python-version: '3.12.5'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd api
        pyenv install 3.12.5
        pip install poetry
        poetry install
        python -m poetry shell
    - name: Lint with Ruff
      run: |
        cd api
        ruff check api/main.py
    - name: Test with pytest
      run: |
        pytest tests 
