name: Python package

on: 
  push:
    branches:
      - feature/api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.5'

    - name: Install Poetry
      run: |
        cd api
        python -m pip install --upgrade pip
        python -m pip install poetry

    - name: Install dependencies
      run: |
        cd api
        poetry install

    - name: Lint with Ruff
      run: |
        cd api
        ruff check api/main.py

    - name: Test with pytest
      run: |
        cd api
        pytest tests
