name: Publish

on:
  push:
    branches:
      - fix/api/publish
    paths:
      - "**/pyproject.toml"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if version has changed
        run: |
          if ! git diff HEAD^ HEAD -- api/pyproject.toml | grep -q "version"; then
            exit 1
          fi
            
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          cd api
          poetry install

      - name: Build and publish package
        run: |
          cd api
          poetry config pypi-token.pypi ${{ secrets.URL_SHORTENER_PUBLISH_TOKEN }}
          poetry publish --build
          sleep 10

      - name: Check version
        id: get_version
        run: |
          cd api
          export VERSION=$(cat pyproject.toml | grep "^version =" | grep -Po '\d+\.\d+\.\d\w+')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build docker image and publish
        run: |
          while true; do
            if python -m pip search "neojelll-url-shortener-api==${{ env.VERSION }}" | grep -q "neojelll-url-shortener-api==${VERSION}"; then
              break
            else
                sleep 2
            fi
          done
          docker build --build-arg VERSION=${{ env.VERSION }} -t ghcr.io/neojelll/url-shortener-api:${{ env.VERSION }} .
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io --username neojelll --password-stdin
          docker push ghcr.io/neojelll/url-shortener-api:${{ env.VERSION }}
